version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "shipengqi"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"